"""Add category, target_date, and progress to Goal model

Revision ID: 3aa1499eb83d
Revises: 1a2cb08491e1
Create Date: 2026-02-10 16:39:20.824347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3aa1499eb83d'
down_revision = '1a2cb08491e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='Personal'))
        batch_op.add_column(sa.Column('target_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('target_date')
        batch_op.drop_column('category')

    op.drop_table('milestone')
    # ### end Alembic commands ###