"""Add subgoals and network alerts

Revision ID: 7b902270fe0d
Revises: 3aa1499eb83d
Create Date: 2026-02-10 19:54:24.253786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b902270fe0d'
down_revision = '3aa1499eb83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['network_contact.id'], name='fk_network_alert_contact_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_network_alert_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_goal_parent_id', 'goal', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_goal_parent_id', type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.drop_table('network_alert')
    # ### end Alembic commands ###
